### ISSUE TITLE
[Build] cudnn 8 can't be found

### ISSUE THREAD

**Issue by svenstaro** [arrayfire/arrayfire#2935]
Description
===========

Arch Linux is currently trying to do the CUDA 11/cuDNN 8 rebuild and we're currently blocked by Arrayfire.

This is Arrayfire 3.7.1. During configuring, we get

```
-- Could NOT find cuDNN: Found unsuitable version ".", but required is at least "4.0" (found /usr/lib/libcudnn.so)
```

The same thing worked fine with cuDNN 7.5.

Error Log
---------

```
==> Starting build()...
-- The C compiler identification is GNU 10.1.0
-- The CXX compiler identification is GNU 10.1.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc - works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ - works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
fatal: not a git repository (or any of the parent directories): .git
-- No git. Setting hash to default
-- Looking for CL_VERSION_2_0
-- Looking for CL_VERSION_2_0 - found
-- Found OpenCL: /usr/lib/libOpenCL.so (found version "2.0") 
-- Downloading https://github.com/KhronosGroup/OpenCL-CLHPP/releases/download/v2.0.10/cl2.hpp
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found CUDA: /opt/cuda (found suitable version "11.0", minimum required is "7.0") 
-- Found PkgConfig: /usr/bin/pkg-config (found version "1.7.3") 
-- Could NOT find cuDNN: Found unsuitable version ".", but required is at least "4.0" (found /usr/lib/libcudnn.so)
-- Found OpenCL: /usr/lib/libOpenCL.so (found suitable version "2.0", minimum required is "1.2") 
-- Found OpenGL: /usr/lib/libGL.so  
-- Found FreeImage: /usr/include  
-- Checking for module 'fftw3'
--   Found fftw3, version 3.3.8
-- Found FFTW: /usr/include  
-- Checking for module 'cblas'
--   Found cblas, version 3.9.0
-- Found CBLAS: /usr/lib/libcblas.so  
-- Found LAPACKE: /usr/lib/liblapacke.so  
CMake Warning (dev) at /usr/share/cmake-3.17/Modules/FindPackageHandleStandardArgs.cmake:272 (message):
  The package name passed to `find_package_handle_standard_args` (LAPACK)
  does not match the name of the calling package (LAPACKE).  This can lead to
  problems in calling code that expects `find_package` result variables
  (e.g., `_FOUND`) to follow a certain pattern.
Call Stack (most recent call first):
  CMakeModules/FindLAPACKE.cmake:153 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  CMakeLists.txt:44 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Found LAPACK: /usr/include  
-- Found Doxygen: /usr/bin/doxygen (found version "1.8.18") found components: doxygen dot 
CMake Warning (dev) at /usr/share/cmake-3.17/Modules/FindPackageHandleStandardArgs.cmake:272 (message):
  The package name passed to `find_package_handle_standard_args` (OpenMP_C)
  does not match the name of the calling package (OpenMP).  This can lead to
  problems in calling code that expects `find_package` result variables
  (e.g., `_FOUND`) to follow a certain pattern.
Call Stack (most recent call first):
  CMakeModules/FindOpenMP.cmake:402 (find_package_handle_standard_args)
  CMakeModules/FindMKL.cmake:67 (find_package)
  CMakeLists.txt:46 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at /usr/share/cmake-3.17/Modules/FindPackageHandleStandardArgs.cmake:272 (message):
  The package name passed to `find_package_handle_standard_args` (OpenMP_CXX)
  does not match the name of the calling package (OpenMP).  This can lead to
  problems in calling code that expects `find_package` result variables
  (e.g., `_FOUND`) to follow a certain pattern.
Call Stack (most recent call first):
  CMakeModules/FindOpenMP.cmake:402 (find_package_handle_standard_args)
  CMakeModules/FindMKL.cmake:67 (find_package)
  CMakeLists.txt:46 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Check size of int
-- Check size of int - done
-- MKL: Thread Layer(Intel OpenMP) Interface(4-byte Integer)
CMake Warning (dev) at /usr/share/cmake-3.17/Modules/FindPackageHandleStandardArgs.cmake:272 (message):
  The package name passed to `find_package_handle_standard_args` (MKL_Shared)
  does not match the name of the calling package (MKL).  This can lead to
  problems in calling code that expects `find_package` result variables
  (e.g., `_FOUND`) to follow a certain pattern.
Call Stack (most recent call first):
  CMakeModules/FindMKL.cmake:354 (find_package_handle_standard_args)
  CMakeLists.txt:46 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Found MKL_Shared: /opt/intel/mkl/include (found version "2020.0.1") 
CMake Warning (dev) at /usr/share/cmake-3.17/Modules/FindPackageHandleStandardArgs.cmake:272 (message):
  The package name passed to `find_package_handle_standard_args` (MKL_Static)
  does not match the name of the calling package (MKL).  This can lead to
  problems in calling code that expects `find_package` result variables
  (e.g., `_FOUND`) to follow a certain pattern.
Call Stack (most recent call first):
  CMakeModules/FindMKL.cmake:363 (find_package_handle_standard_args)
  CMakeLists.txt:46 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Could NOT find MKL: Source the compilervars.sh or mklvars.sh scripts included with your installation of MKL. This script searches for the libraries in MKLROOT, LIBRARY_PATHS(Linux), and LIB(Windows) environment variables (missing: MKL_Core_STATIC_LINK_LIBRARY MKL_Interface_STATIC_LINK_LIBRARY MKL_ThreadLayer_STATIC_LINK_LIBRARY) (found version "2020.0.1")
-- Found Boost: /usr/include (found version "1.72.0")  
Building with NONFREE requires the following patents
Method and apparatus for identifying scale invariant features
in an image and use of same for locating an object in an image, David
G. Lowe, US Patent 6,711,293 (March 23, 2004). Provisional application
filed March 8, 1999. Asignee: The University of British Columbia. For
further details, contact David Lowe (lowe@cs.ubc.ca) or the
University-Industry Liaison Office of the University of British
Columbia.
-- Performing Test has_ignored_attributes_flag
-- Performing Test has_ignored_attributes_flag - Success
-- CUDA_architecture_build_targets: 5.2;5.3;6.0;6.1;6.2;7.0;7.2;7.5;8.0
-- Found OpenCL: /usr/lib/libOpenCL.so (found version "2.0") 
-- Found PythonInterp: /usr/bin/python (found version "3.8.3") 
-- Check if compiler accepts -pthread
-- Check if compiler accepts -pthread - yes
fatal: not a git repository (or any of the parent directories): .git
-- No git. Setting hash to default
fatal: not a git repository (or any of the parent directories): .git
-- No git. Setting hash to default
-- Configuring done
-- Generating done
-- Build files have been written to: /build/arrayfire/src/arrayfire-full-3.7.1/build
```

Build Environment
-----------------
Compiler version: gcc 10.1.0 in general and gcc 9.3.0 for CUDA
Operating system: Arch Linux
Build environment: N/A
CMake variables: N/A

Our cudnn package is built like [this](https://git.archlinux.org/svntogit/community.git/tree/trunk/PKGBUILD?h=packages/cudnn) and contains [these files](https://www.archlinux.org/packages/community-testing/x86_64/cudnn/) (click *View the file list for cudnn*).

**Comment by 9prady9** [comment]
It seems like the version is being incorrectly found/calculated. The message does say `libcudnn.so` is found.

Can you please do `grep -i cudnn ./build/CMakeCache.txt` and share the output here.

**Comment by 9prady9** [comment]
nvm, I found the problem. It is as I expected, cudnn.h header changed, we were reading version info from the header since cudnn doesn't provide cmake config file or package config file.

As the header moved the version info into a separate header, the version info got messed up.

We will look into it.
